// <auto-generated />
namespace E_Bend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editF));
        
        string IMigrationMetadata.Id
        {
            get { return "202010051641323_editF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
